### ISSUE TITLE
EPIC: Get a new job 

### ISSUE THREAD

**Issue by mrwalczyk** [mrwalczyk/mw-resume#1]
- [ ] Update resume experience
  - [ ] Update job experience
  - [ ] Update formatting
- [ ] Look for job postings
  - [ ] Evaluate job posting
  - [ ] Apply to job posting
- [ ] Practice interview 
  - [ ] Practice interview coding
  - [ ] Practice interview hr questions
  - [ ] Practice general interview
- [ ] Interview
  - [ ] Make notes
  - [ ] Post review self evaluation
  - [ ] Post review actions
